version: '3'
services:
  api:
    build:
      context: ./docker/dev
      dockerfile: dev.Dockerfile
    container_name: api
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - API_PORT=$API_PORT
    volumes:
      - .:/usr/src/api
    working_dir: /usr/src/api
    ports:
      - $API_PORT:$API_PORT
    networks:
      - api-network
    command: ./scripts/wait-for.sh db:27017 -- npm run dev
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: db
    volumes:
      - dbdata:/data/db
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  dbdata: